name: money_logger
description: "A simple and efficient personal expense tracker built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- State Management & Architecture ---
  flutter_riverpod: ^2.5.1
  
  # --- Database Lokal Cepat ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # --- Backend & Multi-User (Firebase) ---
  firebase_core: ^2.24.2 
  firebase_auth: ^4.15.2 
  cloud_firestore: ^4.13.6 

  # --- Visualisasi & Utilitas ---
  fl_chart: ^0.68.0          # Statistik/Grafik
  uuid: ^4.3.1               # Membuat ID unik global (Penting untuk Sinkronisasi)
  intl: ^0.20.2              # Format Tanggal & Mata Uang
  
  # --- Export Data (CSV & PDF) ---
  csv: ^5.1.1                # Membuat file CSV
  pdf: ^3.10.6               # Membuat dokumen PDF
  printing: ^5.11.1          # Mencetak/Membagikan PDF
  path_provider: ^2.1.1      # Akses direktori file
  
  # --- Advanced Features ---
  connectivity_plus: ^5.0.2   # Network connectivity
  flutter_local_notifications: ^17.2.0  # Local notifications
  timezone: ^0.9.2            # Timezone support
  image_picker: ^1.0.4       # Photo attachments
  cached_network_image: ^3.3.0 # Image caching
  flutter_localizations:     # Multi-language support
    sdk: flutter
  permission_handler: ^12.0.1
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/images/splash_logo_white.png
  image_dark: assets/images/splash_logo_dark.png
  android: true
  ios: true
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation untuk Hive
  build_runner: ^2.4.8       # Pertahankan
  hive_generator: ^2.0.1     # Pertahankan
  
  # --- Linting (Disesuaikan untuk menghindari konflik analyzer) ---
  # Versi ini lebih konservatif dan compatible dengan Hive Generator.
  flutter_lints: ^3.0.0      # Kita naikkan ke versi terbaru
  custom_lint: ^0.6.4        # Versi yang compatible dengan lint terbaru
  riverpod_lint: ^2.3.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_logo_white.png
    - assets/images/splash_logo_dark.png